<audio id="audio_1"><source src="{{asset('audio/1.oga')}}" type="audio/ogg"></audio>
<audio id="audio_2"><source src="{{asset('audio/2.oga')}}" type="audio/ogg"></audio>
<audio id="audio_3"><source src="{{asset('audio/3.oga')}}" type="audio/ogg"></audio>
<audio id="audio_4"><source src="{{asset('audio/4.oga')}}" type="audio/ogg"></audio>
<audio id="audio_5"><source src="{{asset('audio/5.oga')}}" type="audio/ogg"></audio>
<audio id="audio_6"><source src="{{asset('audio/6.oga')}}" type="audio/ogg"></audio>
<audio id="audio_7"><source src="{{asset('audio/7.oga')}}" type="audio/ogg"></audio>
<audio id="audio_8"><source src="{{asset('audio/8.oga')}}" type="audio/ogg"></audio>
<audio id="audio_9"><source src="{{asset('audio/9.oga')}}" type="audio/ogg"></audio>
<audio id="audio_10"><source src="{{asset('audio/10.oga')}}" type="audio/ogg"></audio>
<audio id="audio_11"><source src="{{asset('audio/11.oga')}}" type="audio/ogg"></audio>
<audio id="audio_12"><source src="{{asset('audio/12.oga')}}" type="audio/ogg"></audio>
<audio id="audio_13"><source src="{{asset('audio/13.oga')}}" type="audio/ogg"></audio>
<audio id="audio_14"><source src="{{asset('audio/14.oga')}}" type="audio/ogg"></audio>
<audio id="audio_15"><source src="{{asset('audio/15.oga')}}" type="audio/ogg"></audio>
<audio id="audio_16"><source src="{{asset('audio/16.oga')}}" type="audio/ogg"></audio>
<audio id="audio_17"><source src="{{asset('audio/17.oga')}}" type="audio/ogg"></audio>
<audio id="audio_18"><source src="{{asset('audio/18.oga')}}" type="audio/ogg"></audio>
<audio id="audio_19"><source src="{{asset('audio/19.oga')}}" type="audio/ogg"></audio>
<audio id="audio_20"><source src="{{asset('audio/20.oga')}}" type="audio/ogg"></audio>
<audio id="audio_21"><source src="{{asset('audio/21.oga')}}" type="audio/ogg"></audio>
<audio id="audio_22"><source src="{{asset('audio/22.oga')}}" type="audio/ogg"></audio>
<audio id="audio_23"><source src="{{asset('audio/23.oga')}}" type="audio/ogg"></audio>
<audio id="audio_24"><source src="{{asset('audio/24.oga')}}" type="audio/ogg"></audio>
<audio id="audio_25"><source src="{{asset('audio/25.oga')}}" type="audio/ogg"></audio>
<audio id="audio_26"><source src="{{asset('audio/26.oga')}}" type="audio/ogg"></audio>
<audio id="audio_27"><source src="{{asset('audio/27.oga')}}" type="audio/ogg"></audio>
<audio id="audio_28"><source src="{{asset('audio/28.oga')}}" type="audio/ogg"></audio>
<audio id="audio_29"><source src="{{asset('audio/29.oga')}}" type="audio/ogg"></audio>
<audio id="audio_30"><source src="{{asset('audio/30.oga')}}" type="audio/ogg"></audio>
<audio id="audio_31"><source src="{{asset('audio/31.oga')}}" type="audio/ogg"></audio>
<audio id="audio_32"><source src="{{asset('audio/32.oga')}}" type="audio/ogg"></audio>
<audio id="audio_33"><source src="{{asset('audio/33.oga')}}" type="audio/ogg"></audio>
<audio id="audio_34"><source src="{{asset('audio/34.oga')}}" type="audio/ogg"></audio>
<audio id="audio_35"><source src="{{asset('audio/35.oga')}}" type="audio/ogg"></audio>
<audio id="audio_36"><source src="{{asset('audio/36.oga')}}" type="audio/ogg"></audio>
<audio id="audio_37"><source src="{{asset('audio/37.oga')}}" type="audio/ogg"></audio>
<audio id="audio_38"><source src="{{asset('audio/38.oga')}}" type="audio/ogg"></audio>
<audio id="audio_39"><source src="{{asset('audio/39.oga')}}" type="audio/ogg"></audio>
<audio id="audio_40"><source src="{{asset('audio/40.oga')}}" type="audio/ogg"></audio>
<audio id="audio_41"><source src="{{asset('audio/41.oga')}}" type="audio/ogg"></audio>
<audio id="audio_42"><source src="{{asset('audio/42.oga')}}" type="audio/ogg"></audio>
<audio id="audio_43"><source src="{{asset('audio/43.oga')}}" type="audio/ogg"></audio>
<audio id="audio_44"><source src="{{asset('audio/44.oga')}}" type="audio/ogg"></audio>
<audio id="audio_45"><source src="{{asset('audio/45.oga')}}" type="audio/ogg"></audio>
<audio id="audio_46"><source src="{{asset('audio/46.oga')}}" type="audio/ogg"></audio>
<audio id="audio_47"><source src="{{asset('audio/47.oga')}}" type="audio/ogg"></audio>
<audio id="audio_48"><source src="{{asset('audio/48.oga')}}" type="audio/ogg"></audio>
<audio id="audio_49"><source src="{{asset('audio/49.oga')}}" type="audio/ogg"></audio>
<audio id="audio_50"><source src="{{asset('audio/50.oga')}}" type="audio/ogg"></audio>
<audio id="audio_51"><source src="{{asset('audio/51.oga')}}" type="audio/ogg"></audio>
<audio id="audio_52"><source src="{{asset('audio/52.oga')}}" type="audio/ogg"></audio>
<audio id="audio_53"><source src="{{asset('audio/53.oga')}}" type="audio/ogg"></audio>
<audio id="audio_54"><source src="{{asset('audio/54.oga')}}" type="audio/ogg"></audio>
<audio id="audio_55"><source src="{{asset('audio/55.oga')}}" type="audio/ogg"></audio>
<audio id="audio_56"><source src="{{asset('audio/56.oga')}}" type="audio/ogg"></audio>
<audio id="audio_57"><source src="{{asset('audio/57.oga')}}" type="audio/ogg"></audio>
<audio id="audio_58"><source src="{{asset('audio/58.oga')}}" type="audio/ogg"></audio>
<audio id="audio_59"><source src="{{asset('audio/59.oga')}}" type="audio/ogg"></audio>
<audio id="audio_60"><source src="{{asset('audio/60.ogg')}}" type="audio/ogg"></audio>
<audio id="audio_61"><source src="{{asset('audio/61.oga')}}" type="audio/ogg"></audio>
<audio id="audio_62"><source src="{{asset('audio/62.oga')}}" type="audio/ogg"></audio>
<audio id="audio_63"><source src="{{asset('audio/63.oga')}}" type="audio/ogg"></audio>
<audio id="audio_64"><source src="{{asset('audio/64.oga')}}" type="audio/ogg"></audio>
<audio id="audio_65"><source src="{{asset('audio/65.oga')}}" type="audio/ogg"></audio>
<audio id="audio_66"><source src="{{asset('audio/66.oga')}}" type="audio/ogg"></audio>
<audio id="audio_67"><source src="{{asset('audio/67.oga')}}" type="audio/ogg"></audio>
<audio id="audio_68"><source src="{{asset('audio/68.oga')}}" type="audio/ogg"></audio>
<audio id="audio_69"><source src="{{asset('audio/69.oga')}}" type="audio/ogg"></audio>
<audio id="audio_70"><source src="{{asset('audio/70.oga')}}" type="audio/ogg"></audio>
<audio id="audio_71"><source src="{{asset('audio/71.oga')}}" type="audio/ogg"></audio>
<audio id="audio_72"><source src="{{asset('audio/72.oga')}}" type="audio/ogg"></audio>
<audio id="audio_73"><source src="{{asset('audio/73.oga')}}" type="audio/ogg"></audio>
<audio id="audio_74"><source src="{{asset('audio/74.oga')}}" type="audio/ogg"></audio>
<audio id="audio_75"><source src="{{asset('audio/75.oga')}}" type="audio/ogg"></audio>
<audio id="audio_76"><source src="{{asset('audio/76.oga')}}" type="audio/ogg"></audio>
<audio id="audio_77"><source src="{{asset('audio/77.oga')}}" type="audio/ogg"></audio>
<audio id="audio_78"><source src="{{asset('audio/78.oga')}}" type="audio/ogg"></audio>
<audio id="audio_79"><source src="{{asset('audio/79.oga')}}" type="audio/ogg"></audio>
<audio id="audio_80"><source src="{{asset('audio/80.oga')}}" type="audio/ogg"></audio>
<audio id="audio_81"><source src="{{asset('audio/81.oga')}}" type="audio/ogg"></audio>
<audio id="audio_82"><source src="{{asset('audio/82.oga')}}" type="audio/ogg"></audio>
<audio id="audio_83"><source src="{{asset('audio/83.oga')}}" type="audio/ogg"></audio>
<audio id="audio_84"><source src="{{asset('audio/84.oga')}}" type="audio/ogg"></audio>
<audio id="audio_85"><source src="{{asset('audio/85.oga')}}" type="audio/ogg"></audio>
<audio id="audio_86"><source src="{{asset('audio/86.oga')}}" type="audio/ogg"></audio>
<audio id="audio_87"><source src="{{asset('audio/87.oga')}}" type="audio/ogg"></audio>
<audio id="audio_88"><source src="{{asset('audio/88.oga')}}" type="audio/ogg"></audio>
<audio id="audio_89"><source src="{{asset('audio/89.oga')}}" type="audio/ogg"></audio>
<audio id="audio_90"><source src="{{asset('audio/90.oga')}}" type="audio/ogg"></audio>

<audio id="carton_lleno"><source src="{{asset('audio/especiales/carton_lleno.ogg')}}" type="audio/ogg"></audio>
<audio id="carton_linea"><source src="{{asset('audio/especiales/carton_linea.ogg')}}" type="audio/ogg"></audio>
<audio id="intento_fallido"><source src="{{asset('audio/especiales/intento_fallido.ogg')}}" type="audio/ogg"></audio>

<audio id="check_linea"><source src="{{asset('audio/especiales/check_linea.oga')}}" type="audio/ogg"></audio>
<audio id="check_bingo"><source src="{{asset('audio/especiales/check_bingo.oga')}}" type="audio/ogg"></audio>

<audio id="linea_incorrecta"><source src="{{asset('audio/especiales/linea_incorrecta.ogg')}}" type="audio/ogg"></audio>
<audio id="bingo_incorrecto"><source src="{{asset('audio/especiales/bingo_incorrecto.ogg')}}" type="audio/ogg"></audio>

